<?php

namespace App\Rules;

class ManifestRule
{
    public function rules(?int $id = null): array
    {
        return [
            'package_id' => ['required', 'exists:packages,id'],
            'in_charge_official_id' => ['nullable', 'integer', 'exists:package_officials,id'],
            'manifest_number' => ['nullable', 'string', 'max:100'],
            'number_format_id' => ['nullable', 'integer', 'exists:numbering_formats,id'],
            'notes' => ['nullable', 'string'],
            'status' => ['nullable', 'string', 'in:open,closed,draft,confirmed,completed,cancelled'],

            // Manifest-level document tabs
            'documents' => ['nullable', 'array'],
            'documents.train_tickets' => ['nullable', 'array'],
            'documents.train_tickets.*.id' => ['nullable', 'integer'],
            'documents.train_tickets.*.file' => ['nullable', 'file', 'max:10240'],
            'documents.train_tickets.*.file_name' => ['nullable', 'string', 'max:255'],
            'documents.train_tickets.*.file_path' => ['nullable', 'string', 'max:255'],
            'documents.train_tickets.*.removed' => ['nullable', 'boolean'],
            'documents.flight_tickets' => ['nullable', 'array'],
            'documents.flight_tickets.*.id' => ['nullable', 'integer'],
            'documents.flight_tickets.*.file' => ['nullable', 'file', 'max:10240'],
            'documents.flight_tickets.*.file_name' => ['nullable', 'string', 'max:255'],
            'documents.flight_tickets.*.file_path' => ['nullable', 'string', 'max:255'],
            'documents.flight_tickets.*.removed' => ['nullable', 'boolean'],
            'documents.visa' => ['nullable', 'array'],
            'documents.visa.*.id' => ['nullable', 'integer'],
            'documents.visa.*.file' => ['nullable', 'file', 'max:10240'],
            'documents.visa.*.file_name' => ['nullable', 'string', 'max:255'],
            'documents.visa.*.file_path' => ['nullable', 'string', 'max:255'],
            'documents.visa.*.removed' => ['nullable', 'boolean'],
            'documents.hotel' => ['nullable', 'array'],
            'documents.hotel.*.id' => ['nullable', 'integer'],
            'documents.hotel.*.file' => ['nullable', 'file', 'max:10240'],
            'documents.hotel.*.file_name' => ['nullable', 'string', 'max:255'],
            'documents.hotel.*.file_path' => ['nullable', 'string', 'max:255'],
            'documents.hotel.*.removed' => ['nullable', 'boolean'],
            'documents.passport' => ['nullable', 'array'],
            'documents.passport.*.id' => ['nullable', 'integer'],
            'documents.passport.*.file' => ['nullable', 'file', 'max:10240'],
            'documents.passport.*.file_name' => ['nullable', 'string', 'max:255'],
            'documents.passport.*.file_path' => ['nullable', 'string', 'max:255'],
            'documents.passport.*.removed' => ['nullable', 'boolean'],
            'documents.photo' => ['nullable', 'array'],
            'documents.photo.*.id' => ['nullable', 'integer'],
            'documents.photo.*.file' => ['nullable', 'file', 'max:10240'],
            'documents.photo.*.file_name' => ['nullable', 'string', 'max:255'],
            'documents.photo.*.file_path' => ['nullable', 'string', 'max:255'],
            'documents.photo.*.removed' => ['nullable', 'boolean'],

            // Members
            'members' => ['nullable', 'array'],
            'members.*.name_as_per_passport' => ['nullable', 'string', 'max:255'],
            'members.*.arabic_name' => ['nullable', 'string', 'max:255'],
            'members.*.customer_confirmation_member_id' => ['nullable', 'integer', 'exists:customer_confirmation_members,id'],
            'members.*.customer_confirmation_id' => ['nullable', 'integer', 'exists:customer_confirmations,id'],
            'members.*.package_official_id' => ['nullable', 'integer', 'exists:package_officials,id'],
            'members.*.role' => ['nullable', 'string', 'max:100'],
            'members.*.relationship' => ['nullable', 'string', 'max:100'],
            'members.*.group_relationship' => ['nullable', 'string', 'max:100'],
            'members.*.sharing_plan' => ['nullable', 'string', 'in:single,double,triple,quad,child_with_bed,child_no_bed,infant'],
            'members.*.group_remarks' => ['nullable', 'string'],
            'members.*.contact_no' => ['nullable', 'string', 'max:255'],
            'members.*.nationality' => ['nullable', 'string', 'max:100'],
            'members.*.gender' => ['nullable', 'string', 'max:50'],
            'members.*.passport_number' => ['nullable', 'string', 'max:50'],
            'members.*.date_of_birth' => ['nullable', 'date'],
            'members.*.date_of_issue' => ['nullable', 'date'],
            'members.*.date_of_expiry' => ['nullable', 'date'],
            'members.*.issue_place' => ['nullable', 'string', 'max:255'],
            'members.*.birth_place' => ['nullable', 'string', 'max:255'],
            'members.*.address' => ['nullable', 'string'],
            'members.*.first_time_umrah' => ['nullable', 'boolean'],
            'members.*.has_chronic_disease' => ['nullable', 'boolean'],
            'members.*.is_using_wheelchair' => ['nullable', 'boolean'],
            'members.*.chronic_disease_details' => ['nullable', 'string'],
            'members.*.passport_path' => ['nullable', 'string', 'max:255'],
            'members.*.photo_path' => ['nullable', 'string', 'max:255'],
            'members.*.remarks' => ['nullable', 'string'],
            'members.*.status' => ['nullable', 'string', 'in:pending_payment,partially_paid,fully_paid,overpaid,cancelled'],
            'members.*.sharing_group_key' => ['nullable', 'string', 'max:255'],
            'members.*.manifest_sharing_group_id' => ['nullable', 'integer'],
            'members.*.sharing_group_id' => ['nullable', 'integer'],
            'members.*.course_1' => ['nullable', 'boolean'],
            'members.*.course_2' => ['nullable', 'boolean'],
            'members.*.lanyard' => ['nullable', 'boolean'],
            'members.*.luggage_tag' => ['nullable', 'boolean'],
            'members.*.cabin_tag' => ['nullable', 'boolean'],
            'members.*.passport_cover' => ['nullable', 'boolean'],
            'members.*.umrah_guidebook' => ['nullable', 'boolean'],
            'members.*.sling_bag' => ['nullable', 'boolean'],
            'members.*.cabin_size_luggage' => ['nullable', 'boolean'],
            'members.*.umrah_essentials' => ['nullable', 'boolean'],
            'members.*.receipt_documents' => ['nullable', 'array'],
            'members.*.receipt_documents.*.id' => ['nullable', 'integer'],
            'members.*.receipt_documents.*.file' => ['nullable', 'file', 'max:10240'],
            'members.*.receipt_documents.*.file_name' => ['nullable', 'string', 'max:255'],
            'members.*.receipt_documents.*.file_path' => ['nullable', 'string', 'max:255'],
            'members.*.receipt_documents.*.removed' => ['nullable', 'boolean'],
            'members.*.passport_documents' => ['nullable', 'array'],
            'members.*.passport_documents.*.id' => ['nullable', 'integer'],
            'members.*.passport_documents.*.file' => ['nullable', 'file', 'max:10240'],
            'members.*.passport_documents.*.file_name' => ['nullable', 'string', 'max:255'],
            'members.*.passport_documents.*.file_path' => ['nullable', 'string', 'max:255'],
            'members.*.passport_documents.*.removed' => ['nullable', 'boolean'],
            'members.*.photo_documents' => ['nullable', 'array'],
            'members.*.photo_documents.*.id' => ['nullable', 'integer'],
            'members.*.photo_documents.*.file' => ['nullable', 'file', 'max:10240'],
            'members.*.photo_documents.*.file_name' => ['nullable', 'string', 'max:255'],
            'members.*.photo_documents.*.file_path' => ['nullable', 'string', 'max:255'],
            'members.*.photo_documents.*.removed' => ['nullable', 'boolean'],

            // Dedicated member receipt document section
            'manifest_member_receipts' => ['nullable', 'array'],
            'manifest_member_receipts.*.manifest_member_id' => ['nullable', 'integer', 'exists:manifest_members,id'],
            'manifest_member_receipts.*.customer_confirmation_member_id' => ['nullable', 'integer', 'exists:customer_confirmation_members,id'],
            'manifest_member_receipts.*.receipt_documents' => ['nullable', 'array'],
            'manifest_member_receipts.*.receipt_documents.*.id' => ['nullable', 'integer'],
            'manifest_member_receipts.*.receipt_documents.*.file' => ['nullable', 'file', 'max:10240'],
            'manifest_member_receipts.*.receipt_documents.*.file_name' => ['nullable', 'string', 'max:255'],
            'manifest_member_receipts.*.receipt_documents.*.file_path' => ['nullable', 'string', 'max:255'],
            'manifest_member_receipts.*.receipt_documents.*.removed' => ['nullable', 'boolean'],

            // Rooms
            'rooms' => ['nullable', 'array'],
            'rooms.*.location' => ['nullable', 'string', 'max:255'],
            'rooms.*.sort_order' => ['nullable', 'integer', 'min:1'],
            'rooms.*.group_relationship' => ['nullable', 'string', 'max:100'],
            'rooms.*.relationship' => ['nullable', 'string', 'max:100'],
            'rooms.*.room_number' => ['nullable', 'string', 'max:50'],
            'rooms.*.room_type' => ['nullable', 'string', 'in:single,twin,double,triple,quad'],
            'rooms.*.bed_type' => ['nullable', 'string', 'in:single,king,queen'],
            'rooms.*.capacity' => ['nullable', 'integer', 'min:1'],
            'rooms.*.status' => ['nullable', 'string', 'in:pending,filled,finalized'],
            'rooms.*.room_label' => ['nullable', 'string', 'max:255'],
            'rooms.*.meal' => ['nullable', 'string', 'max:255'],
            'rooms.*.number_of_beds_checked' => ['nullable', 'boolean'],
            'rooms.*.remarks' => ['nullable', 'string'],
            'rooms.*.members' => ['nullable', 'array'],
            'rooms.*.members.*.id' => ['nullable', 'integer'],
            'rooms.*.members.*.manifest_member_id' => ['nullable', 'integer'],
            'rooms.*.members.*.customer_confirmation_member_id' => ['nullable', 'integer', 'exists:customer_confirmation_members,id'],
            'rooms.*.members.*.package_official_id' => ['nullable', 'integer', 'exists:package_officials,id'],
            'rooms.*.members.*.sort_order' => ['nullable', 'integer', 'min:1'],
            'rooms.*.members.*.remarks' => ['nullable', 'string'],
        ];
    }

    /**
     * Validation rules for individual room CRUD operations.
     */
    public function roomRules(): array
    {
        return [
            'location' => ['nullable', 'string', 'max:255'],
            'sort_order' => ['nullable', 'integer', 'min:1'],
            'group_relationship' => ['nullable', 'string', 'max:100'],
            'relationship' => ['nullable', 'string', 'max:100'],
            'room_number' => ['nullable', 'string', 'max:50'],
            'room_type' => ['nullable', 'string', 'in:single,twin,double,triple,quad'],
            'bed_type' => ['nullable', 'string', 'in:single,king,queen'],
            'capacity' => ['nullable', 'integer', 'min:1'],
            'status' => ['nullable', 'string', 'in:pending,filled,finalized'],
            'room_label' => ['nullable', 'string', 'max:255'],
            'meal' => ['nullable', 'string', 'max:255'],
            'remarks' => ['nullable', 'string'],
            'members' => ['nullable', 'array'],
            'members.*.id' => ['nullable', 'integer'],
            'members.*.manifest_member_id' => ['nullable', 'integer'],
            'members.*.customer_confirmation_member_id' => ['nullable', 'integer', 'exists:customer_confirmation_members,id'],
            'members.*.package_official_id' => ['nullable', 'integer', 'exists:package_officials,id'],
            'members.*.sort_order' => ['nullable', 'integer', 'min:1'],
            'members.*.remarks' => ['nullable', 'string'],
        ];
    }
}
