<?php

namespace Database\Seeders\Tms;

use App\Models\CustomerConfirmationMember;
use App\Models\Manifest;
use App\Models\ManifestMember;
use App\Models\ManifestRoom;
use App\Models\ManifestRoomMember;
use App\Models\ManifestSharingGroup;
use App\Models\Package;
use Illuminate\Database\Seeder;

class ManifestSeeder extends Seeder
{
    public function run(): void
    {
        $packages = Package::query()->with('officials')->orderBy('id')->get();

        foreach ($packages as $package) {
            $manifest = Manifest::query()->firstOrCreate(
                ['package_id' => $package->id],
                ['notes' => 'Generated by manifest seeder']
            );

            $groupByConfirmation = [];

            $eligibleMembers = CustomerConfirmationMember::query()
                ->with(['confirmation', 'customer'])
                ->whereHas('confirmation', function ($query) use ($package): void {
                    $query->where('package_id', $package->id);
                })
                ->whereIn('status', ['partially_paid', 'fully_paid', 'confirmed'])
                ->orderBy('customer_confirmation_id')
                ->orderBy('id')
                ->get();

            foreach ($eligibleMembers as $member) {
                $confirmationId = (int) $member->customer_confirmation_id;

                if (! isset($groupByConfirmation[$confirmationId])) {
                    $groupByConfirmation[$confirmationId] = ManifestSharingGroup::query()->firstOrCreate(
                        [
                            'manifest_id' => $manifest->id,
                            'customer_confirmation_id' => $confirmationId,
                        ],
                        [
                            'sort_order' => count($groupByConfirmation) + 1,
                            'group_relationship' => 'family',
                            'remarks' => sprintf('Group %d', $confirmationId),
                        ]
                    )->id;
                }

                ManifestMember::query()->updateOrCreate(
                    [
                        'manifest_id' => $manifest->id,
                        'customer_confirmation_member_id' => $member->id,
                    ],
                    [
                        'manifest_sharing_group_id' => $groupByConfirmation[$confirmationId],
                        'relationship' => $member->relationship ?: 'member',
                        'sharing_plan' => $member->sharing_plan ?: 'double',
                        'name' => $member->customer?->user?->name,
                        'contact_number' => $member->customer?->user?->contact_number,
                        'nationality' => $member->customer?->nationality,
                        'passport_number' => $member->customer?->passport_number,
                        'gender' => $member->customer?->gender,
                        'date_of_birth' => $member->customer?->date_of_birth,
                        'passport_issue_date' => $member->customer?->passport_issue_date,
                        'passport_expiry_date' => $member->customer?->passport_expiry_date,
                        'passport_place_of_issue' => $member->customer?->passport_place_of_issue,
                        'place_of_birth' => $member->customer?->place_of_birth,
                        'remarks' => null,
                    ]
                );
            }

            if ($package->officials->isNotEmpty()) {
                $officialGroup = ManifestSharingGroup::query()->firstOrCreate(
                    [
                        'manifest_id' => $manifest->id,
                        'customer_confirmation_id' => null,
                        'remarks' => '[package-official]',
                    ],
                    [
                        'sort_order' => ManifestSharingGroup::query()->where('manifest_id', $manifest->id)->count() + 1,
                        'group_relationship' => 'official',
                    ]
                );

                foreach ($package->officials as $official) {
                    ManifestMember::query()->updateOrCreate(
                        [
                            'manifest_id' => $manifest->id,
                            'package_official_id' => $official->id,
                        ],
                        [
                            'manifest_sharing_group_id' => $officialGroup->id,
                            'relationship' => $official->type ?: 'official',
                            'sharing_plan' => 'single',
                            'name' => $official->name,
                            'contact_number' => $official->contact_number,
                            'nationality' => $official->nationality,
                            'passport_number' => $official->passport_number,
                            'gender' => $official->gender,
                            'date_of_birth' => $official->date_of_birth,
                            'passport_issue_date' => $official->passport_issue_date,
                            'passport_expiry_date' => $official->passport_expiry_date,
                            'passport_place_of_issue' => $official->passport_place_of_issue,
                            'place_of_birth' => $official->place_of_birth,
                            'remarks' => '[package-official]'.($official->type ? ' '.$official->type : ''),
                        ]
                    );
                }
            }

            $manifestMembers = ManifestMember::query()
                ->where('manifest_id', $manifest->id)
                ->orderBy('id')
                ->get();

            ManifestRoomMember::query()
                ->whereIn('manifest_room_id', ManifestRoom::query()->where('manifest_id', $manifest->id)->pluck('id'))
                ->delete();
            ManifestRoom::query()->where('manifest_id', $manifest->id)->delete();

            $membersByRoomType = $manifestMembers->groupBy(function (ManifestMember $member): string {
                return match ($member->sharing_plan) {
                    'single' => 'single',
                    'triple' => 'triple',
                    'quad' => 'quad',
                    default => 'double',
                };
            });

            $roomSort = 1;

            foreach ($membersByRoomType as $roomType => $members) {
                $capacity = match ($roomType) {
                    'single' => 1,
                    'triple' => 3,
                    'quad' => 4,
                    default => 2,
                };

                foreach ($members->chunk($capacity) as $chunkIndex => $memberChunk) {
                    $room = ManifestRoom::query()->create([
                        'manifest_id' => $manifest->id,
                        'sort_order' => $roomSort++,
                        'room_type' => $roomType,
                        'capacity' => $capacity,
                        'status' => 'open',
                        'room_label' => strtoupper($roomType).'-'.($chunkIndex + 1),
                    ]);

                    foreach ($memberChunk->values() as $memberIndex => $manifestMember) {
                        ManifestRoomMember::query()->create([
                            'manifest_room_id' => $room->id,
                            'manifest_member_id' => $manifestMember->id,
                            'sort_order' => $memberIndex + 1,
                        ]);
                    }
                }
            }
        }
    }
}
