import { z } from 'zod';

export const privateEnquirySchema = z.object({
    id: z.number().optional(),
    enquiry_id: z.number().nullable().optional(),
    status: z.string().optional(),
    status_label: z.string().optional(),
    name: z.string().optional(),
    contact_number: z.string().optional(),
    email: z.string().optional(),
    passport_expiry_date: z.string().optional(),
    departure_date: z.string().optional(),
    return_date: z.string().optional(),
    no_of_pax: z.number().optional(),
    no_of_children: z.number().optional(),
    airline: z.string().optional(),
    class: z.string().optional(),
    require_mutawif: z.boolean().optional(),
    require_umrah_course: z.boolean().optional(),
    require_umrah_official: z.boolean().optional(),
    makkah_or_madinah_first: z.string().optional(),
    no_of_nights_makkah: z.string().optional(),
    hotel_makkah: z.string().optional(),
    meals_makkah: z.string().optional(),
    no_of_nights_madinah: z.string().optional(),
    hotel_madinah: z.string().optional(),
    meals_madinah: z.string().optional(),
    land_transfer: z.string().optional(),
    add_on_speed_train: z.boolean().optional(),
    require_meet_greet: z.boolean().optional(),
    require_mutawiffah_ustazah_rawdah: z.boolean().optional(),
    madinah_tour_with_mutawif: z.boolean().optional(),
    makkah_tour_with_mutawif: z.boolean().optional(),
    has_chronic_disease: z.boolean().optional(),
    chronic_disease_details: z.string().nullable().optional(),
    need_wheelchair: z.string().optional(),
    other_remarks: z.string().nullable().optional(),
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
});

export type PrivateEnquirySchema = z.infer<typeof privateEnquirySchema>;
