import {
    type ManifestSchema,
    type RoomSchema,
    type TravelerSchema,
} from './schema';

/**
 * Dummy data untuk testing Manifest Form
 * Berisi semua input fields yang diperlukan sesuai dengan migration terbaru
 */

export const dummyManifestData: ManifestSchema = {
    id: 1,
    package_id: 1,
    reference_number: 'UMRAH-2024-001',
    company_address: '123 Jalan Commerce, Kuala Lumpur, Malaysia',
    company_phone: '+60-3-1234-5678',
    departure_date: '2024-03-15',
    return_date: '2024-03-29',
    duration: '14 Days / 13 Nights',
    makkah_hotel: 'Dar Al Eiman Al Centraliyah',
    makkah_check_in: '2024-03-16',
    makkah_check_out: '2024-03-24',
    madinah_hotel: 'Al Ansar Hotel',
    madinah_check_in: '2024-03-24',
    madinah_check_out: '2024-03-28',
    flight_details: {
        outbound: {
            airline: 'Malaysia Airlines',
            flight_number: 'MH 1234',
            departure_airport: 'KUL',
            arrival_airport: 'JED',
            departure_date: '2024-03-15',
            departure_time: '22:00',
            arrival_date: '2024-03-16',
            arrival_time: '05:30',
        },
        return: {
            airline: 'Malaysia Airlines',
            flight_number: 'MH 1235',
            departure_airport: 'JED',
            arrival_airport: 'KUL',
            departure_date: '2024-03-28',
            departure_time: '14:00',
            arrival_date: '2024-03-29',
            arrival_time: '08:30',
        },
    },
    notes: 'This is a standard Umrah package with 14 days duration. All participants must have valid passports.',
    first_meal: 'Lunch',
    last_meal: 'Breakfast',
    status: 'confirmed',
    travelers: [
        {
            sn: 1,
            name_as_per_passport: 'Ahmad Bin Abdullah',
            customer_id: 1001,
            ppt_no: 'A12345678',
            date_of_issue: '2020-01-15',
            date_of_expiry: '2030-01-14',
            issue_place: 'Kuala Lumpur',
            date_of_birth: '1980-05-10',
            age: 44,
            contact_no: '+60-10-1234-5678',
            gender: 'Male',
            birth_place: 'Kuala Lumpur',
            date_of_sign_up: '2024-01-10',
            is_first_time_umrah: false,
            package_price: 3500,
            discount: 0,
            date_of_deposit_payment: '2024-01-10',
            deposit_payment: 3500,
            date_of_second_payment: undefined,
            second_payment: 0,
            balance_due: 0,
            is_fully_paid: true,
            receipt_no: 'RCP-001',
            remarks: 'Group leader',
        },
        {
            sn: 2,
            name_as_per_passport: 'Siti Binti Abdullah',
            customer_id: 1002,
            ppt_no: 'A87654321',
            date_of_issue: '2019-06-20',
            date_of_expiry: '2029-06-19',
            issue_place: 'Kuala Lumpur',
            date_of_birth: '1982-03-15',
            age: 42,
            contact_no: '+60-10-8765-4321',
            gender: 'Female',
            birth_place: 'Kuala Lumpur',
            date_of_sign_up: '2024-01-10',
            is_first_time_umrah: false,
            package_price: 3500,
            discount: 0,
            date_of_deposit_payment: '2024-01-10',
            deposit_payment: 3500,
            date_of_second_payment: undefined,
            second_payment: 0,
            balance_due: 0,
            is_fully_paid: true,
            receipt_no: 'RCP-002',
            remarks: 'Group spouse',
        },
        {
            sn: 3,
            name_as_per_passport: 'Muhammad Farhan Abdullah',
            customer_id: 1003,
            ppt_no: 'A11223344',
            date_of_issue: '2021-08-10',
            date_of_expiry: '2031-08-09',
            issue_place: 'Kuala Lumpur',
            date_of_birth: '2005-12-22',
            age: 18,
            contact_no: '+60-10-5555-6666',
            gender: 'Male',
            birth_place: 'Kuala Lumpur',
            date_of_sign_up: '2024-01-10',
            is_first_time_umrah: true,
            package_price: 3200,
            discount: 0,
            date_of_deposit_payment: '2024-01-15',
            deposit_payment: 2500,
            date_of_second_payment: undefined,
            second_payment: 0,
            balance_due: 700,
            is_fully_paid: false,
            receipt_no: 'RCP-003',
            remarks: 'Young adult',
        },
        {
            sn: 4,
            name_as_per_passport: 'Fatimah Binti Ahmad',
            customer_id: 1004,
            ppt_no: 'A55667788',
            date_of_issue: '2018-04-05',
            date_of_expiry: '2028-04-04',
            issue_place: 'Kuala Lumpur',
            date_of_birth: '1985-07-18',
            age: 39,
            contact_no: '+60-10-2222-3333',
            gender: 'Female',
            birth_place: 'Kuala Lumpur',
            date_of_sign_up: '2024-01-10',
            is_first_time_umrah: false,
            package_price: 3500,
            discount: 0,
            date_of_deposit_payment: '2024-01-10',
            deposit_payment: 3500,
            date_of_second_payment: undefined,
            second_payment: 0,
            balance_due: 0,
            is_fully_paid: true,
            receipt_no: 'RCP-004',
            remarks: 'Senior member',
        },
        {
            sn: 5,
            name_as_per_passport: 'Hassan Bin Ahmad',
            customer_id: 1005,
            ppt_no: 'A99887766',
            date_of_issue: '2022-02-14',
            date_of_expiry: '2032-02-13',
            issue_place: 'Kuala Lumpur',
            date_of_birth: '1988-09-30',
            age: 36,
            contact_no: '+60-10-4444-5555',
            gender: 'Male',
            birth_place: 'Kuala Lumpur',
            date_of_sign_up: '2024-01-10',
            is_first_time_umrah: false,
            package_price: 3200,
            discount: 0,
            date_of_deposit_payment: '2024-01-10',
            deposit_payment: 3200,
            date_of_second_payment: undefined,
            second_payment: 0,
            balance_due: 0,
            is_fully_paid: true,
            receipt_no: 'RCP-005',
            remarks: 'Standard participant',
        },
    ],
    rooms: [
        {
            name_as_per_passport: 'Ahmad Bin Abdullah',
            relationship: 'Self',
            passport_no: 'A12345678',
            room_no: '101',
            room_number: '101',
            location: 'Makkah',
            room_type: 'Double',
            bed_type: 'King',
            date_of_birth: '1980-05-10',
            age: 44,
            no_of_beds_checked: 1,
            meal: 'Breakfast',
            remarks: 'Group leader room',
        },
        {
            name_as_per_passport: 'Siti Binti Abdullah',
            relationship: 'Spouse',
            passport_no: 'A87654321',
            room_no: '101',
            room_number: '101',
            location: 'Makkah',
            room_type: 'Double',
            bed_type: 'King',
            date_of_birth: '1982-03-15',
            age: 42,
            no_of_beds_checked: 1,
            meal: 'Breakfast',
            remarks: 'Shared with spouse',
        },
        {
            name_as_per_passport: 'Muhammad Farhan Abdullah',
            relationship: 'Son',
            passport_no: 'A11223344',
            room_no: '102',
            room_number: '102',
            location: 'Makkah',
            room_type: 'Triple',
            bed_type: 'Single',
            date_of_birth: '2005-12-22',
            age: 18,
            no_of_beds_checked: 1,
            meal: 'Breakfast',
            remarks: 'Young adult',
        },
        {
            name_as_per_passport: 'Fatimah Binti Ahmad',
            relationship: 'Sister',
            passport_no: 'A55667788',
            room_no: '103',
            room_number: '103',
            location: 'Makkah',
            room_type: 'Double',
            bed_type: 'King',
            date_of_birth: '1985-07-18',
            age: 39,
            no_of_beds_checked: 1,
            meal: 'Breakfast',
            remarks: 'Senior member',
        },
        {
            name_as_per_passport: 'Hassan Bin Ahmad',
            relationship: 'Brother',
            passport_no: 'A99887766',
            room_no: '102',
            room_number: '102',
            location: 'Makkah',
            room_type: 'Triple',
            bed_type: 'Single',
            date_of_birth: '1988-09-30',
            age: 36,
            no_of_beds_checked: 1,
            meal: 'Breakfast',
            remarks: 'Standard participant',
        },
    ],
};

export const dummyTravelerData: TravelerSchema = {
    sn: 6,
    name_as_per_passport: 'Nurul Asyiqin Binti Hassan',
    customer_id: 1006,
    ppt_no: 'A44556677',
    date_of_issue: '2019-11-08',
    date_of_expiry: '2029-11-07',
    issue_place: 'Kuala Lumpur',
    date_of_birth: '2000-03-25',
    age: 24,
    contact_no: '+60-10-9999-8888',
    gender: 'Female',
    birth_place: 'Kuala Lumpur',
    date_of_sign_up: '2024-01-20',
    is_first_time_umrah: true,
    package_price: 2800,
    discount: 0,
    date_of_deposit_payment: '2024-01-20',
    deposit_payment: 1400,
    date_of_second_payment: undefined,
    second_payment: 0,
    balance_due: 1400,
    is_fully_paid: false,
    receipt_no: 'RCP-006',
    remarks: 'Young adult, first time Umrah',
};

export const dummyRoomData: RoomSchema = {
    name_as_per_passport: 'Nurul Asyiqin Binti Hassan',
    relationship: 'Niece',
    passport_no: 'A44556677',
    room_no: '104',
    room_number: '104',
    location: 'Makkah',
    room_type: 'Single',
    bed_type: 'Single',
    date_of_birth: '2000-03-25',
    age: 24,
    no_of_beds_checked: 1,
    meal: 'Breakfast',
    remarks: 'Young adult, first time Umrah',
};

export const packageOptions = [
    { value: 1, label: 'Standard Umrah Package' },
    { value: 2, label: 'Premium Umrah Package' },
    { value: 3, label: 'VIP Umrah Package' },
    { value: 4, label: 'Family Umrah Package' },
];

export const customerConfirmationsDummyData = [
    {
        id: 1,
        package_room_type: 'Double',
        enquiry_id: 101,
        enquiry_type: 'Individual',
        enquiry_status: 'confirmed',
        leader_name: 'Ahmad Bin Abdullah',
        leader_email: 'ahmad@email.com',
        leader_contact: '+60-10-1234-5678',
        leader_customer_number: 'CUST-001',
        member_count: 5,
        created_at: '2024-01-10',
        members: [
            {
                id: 1,
                customer_id: 1001,
                is_leader: true,
                name: 'Ahmad Bin Abdullah',
                email: 'ahmad@email.com',
                contact: '+60-10-1234-5678',
                customer_number: 'CUST-001',
                nric_number: '800510-10-1234',
                passport_number: 'A12345678',
                passport_issue_date: '2020-01-15',
                passport_expiry_date: '2030-01-14',
                passport_place_of_issue: 'Kuala Lumpur',
                date_of_birth: '1980-05-10',
                age: 44,
            },
            {
                id: 2,
                customer_id: 1002,
                is_leader: false,
                name: 'Siti Binti Abdullah',
                email: 'siti@email.com',
                contact: '+60-10-8765-4321',
                customer_number: 'CUST-002',
                nric_number: '820315-10-5678',
                passport_number: 'A87654321',
                passport_issue_date: '2019-06-20',
                passport_expiry_date: '2029-06-19',
                passport_place_of_issue: 'Kuala Lumpur',
                date_of_birth: '1982-03-15',
                age: 42,
            },
            {
                id: 3,
                customer_id: 1003,
                is_leader: false,
                name: 'Muhammad Farhan Abdullah',
                email: 'farhan@email.com',
                contact: '+60-10-5555-6666',
                customer_number: 'CUST-003',
                nric_number: '051222-10-9999',
                passport_number: 'A11223344',
                passport_issue_date: '2021-08-10',
                passport_expiry_date: '2031-08-09',
                passport_place_of_issue: 'Kuala Lumpur',
                date_of_birth: '2005-12-22',
                age: 18,
            },
            {
                id: 4,
                customer_id: 1004,
                is_leader: false,
                name: 'Fatimah Binti Ahmad',
                email: 'fatimah@email.com',
                contact: '+60-10-2222-3333',
                customer_number: 'CUST-004',
                nric_number: '850718-10-1111',
                passport_number: 'A55667788',
                passport_issue_date: '2018-04-05',
                passport_expiry_date: '2028-04-04',
                passport_place_of_issue: 'Kuala Lumpur',
                date_of_birth: '1985-07-18',
                age: 39,
            },
            {
                id: 5,
                customer_id: 1005,
                is_leader: false,
                name: 'Hassan Bin Ahmad',
                email: 'hassan@email.com',
                contact: '+60-10-4444-5555',
                customer_number: 'CUST-005',
                nric_number: '880930-10-2222',
                passport_number: 'A99887766',
                passport_issue_date: '2022-02-14',
                passport_expiry_date: '2032-02-13',
                passport_place_of_issue: 'Kuala Lumpur',
                date_of_birth: '1988-09-30',
                age: 36,
            },
        ],
    },
    {
        id: 2,
        package_room_type: 'Triple',
        enquiry_id: 102,
        enquiry_type: 'Group',
        enquiry_status: 'confirmed',
        leader_name: 'Zainal Abidin',
        leader_email: 'zainal@email.com',
        leader_contact: '+60-11-7777-8888',
        leader_customer_number: 'CUST-010',
        member_count: 3,
        created_at: '2024-01-12',
        members: [
            {
                id: 6,
                customer_id: 2001,
                is_leader: true,
                name: 'Zainal Abidin',
                email: 'zainal@email.com',
                contact: '+60-11-7777-8888',
                customer_number: 'CUST-010',
                nric_number: '750620-10-3456',
                passport_number: 'B12345678',
                passport_issue_date: '2017-05-20',
                passport_expiry_date: '2027-05-19',
                passport_place_of_issue: 'Penang',
                date_of_birth: '1975-06-20',
                age: 49,
            },
            {
                id: 7,
                customer_id: 2002,
                is_leader: false,
                name: 'Aminah Binti Zainal',
                email: 'aminah@email.com',
                contact: '+60-11-9999-0000',
                customer_number: 'CUST-011',
                nric_number: '780814-10-4567',
                passport_number: 'B87654321',
                passport_issue_date: '2018-03-10',
                passport_expiry_date: '2028-03-09',
                passport_place_of_issue: 'Penang',
                date_of_birth: '1978-08-14',
                age: 46,
            },
            {
                id: 8,
                customer_id: 2003,
                is_leader: false,
                name: 'Khairul Bin Zainal',
                email: 'khairul@email.com',
                contact: '+60-11-6666-7777',
                customer_number: 'CUST-012',
                nric_number: '020310-10-5678',
                passport_number: 'B11223344',
                passport_issue_date: '2020-11-15',
                passport_expiry_date: '2030-11-14',
                passport_place_of_issue: 'Penang',
                date_of_birth: '2002-03-10',
                age: 22,
            },
        ],
    },
];
